<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Country1 as Country;
use App\Models\State1  as State;
use App\Models\City1  as City;

class CountryStateCitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
    // $country=Country::create($country=Country::create(['name'=>'United State']));
    // $state=State::create($country=Country::create(['country_id'=>$country->id;'name'=>'Florida']));
    // City::create($country=Country::create(['state_id'=>$state->id; 'name'=>'Miami']));
    // City::create($country=Country::create(['state_id'=>$state->id; 'name'=>'Tampa']));

    // $country=Country::create($country=Country::create(['name'=>'India']));

    // $state=State::create($country=Country::create(['country_id'=>$country->id;'name'=>'Gujrat']));
    // City::create($country=Country::create(['state_id'=>$state->id; 'name'=>'Surat']));
    // City::create($country=Country::create(['state_id'=>$state->id; 'name'=>'Rajkot']));
    // City::create($country=Country::create(['state_id'=>$state->id; 'name'=>'Himmantnagar']));
    // City::create($country=Country::create(['state_id'=>$state->id; 'name'=>'Vadodara']));
    // City::create($country=Country::create(['state_id'=>$state->id; 'name'=>'Bhavnagar']));
    // City::create($country=Country::create(['state_id'=>$state->id; 'name'=>'Jamnagar']));
    // City::create($country=Country::create(['state_id'=>$state->id; 'name'=>'Junagadh']));
    // City::create($country=Country::create(['state_id'=>$state->id; 'name'=>'Anand']));
    // City::create($country=Country::create(['state_id'=>$state->id; 'name'=>'Navsari']));
    // City::create($country=Country::create(['state_id'=>$state->id; 'name'=>'Morbi']));
    // City::create($country=Country::create(['state_id'=>$state->id; 'name'=>'Rajkot']));
    // City::create($country=Country::create(['state_id'=>$state->id; 'name'=>'Surendranagar']));
    // City::create($country=Country::create(['state_id'=>$state->id; 'name'=>'Surat']));
    // City::create($country=Country::create(['state_id'=>$state->id; 'name'=>'Bharuch']));
    // City::create($country=Country::create(['state_id'=>$state->id; 'name'=>'Mehsana']));
    // City::create($country=Country::create(['state_id'=>$state->id; 'name'=>'Bhuj']));
    // City::create($country=Country::create(['state_id'=>$state->id; 'name'=>'Porbandar']));
    // City::create($country=Country::create(['state_id'=>$state->id; 'name'=>'Palanpur']));
    // City::create($country=Country::create(['state_id'=>$state->id; 'name'=>'Valsad']));
    // City::create($country=Country::create(['state_id'=>$state->id; 'name'=>'Vapi']));
    // City::create($country=Country::create(['state_id'=>$state->id; 'name'=>'Gondal']));
    // City::create($country=Country::create(['state_id'=>$state->id; 'name'=>'Veraval']));
    // City::create($country=Country::create(['state_id'=>$state->id; 'name'=>'Godhra']));
    // City::create($country=Country::create(['state_id'=>$state->id; 'name'=>'Patan']));
    // City::create($country=Country::create(['state_id'=>$state->id; 'name'=>'Kalol']));
    // City::create($country=Country::create(['state_id'=>$state->id; 'name'=>'Dahod']));
    // City::create($country=Country::create(['state_id'=>$state->id; 'name'=>'Botad']));
    // City::create($country=Country::create(['state_id'=>$state->id; 'name'=>'Amreli']));
    // City::create($country=Country::create(['state_id'=>$state->id; 'name'=>'Deesa']));
    // City::create($country=Country::create(['state_id'=>$state->id; 'name'=>'Jetpur']));


    // $state=State::create($country=Country::create(['country_id'=>$country->id;'name'=>'Madhya-Pradesh']));
    // City::create($country=Country::create(['state_id'=>$state->id; 'name'=>'Bhopal']));
    // City::create($country=Country::create(['state_id'=>$state->id; 'name'=>'Burhanpur']));
    // City::create($country=Country::create(['state_id'=>$state->id; 'name'=>'Gwalior']));
    // City::create($country=Country::create(['state_id'=>$state->id; 'name'=>'Indore']));
    // City::create($country=Country::create(['state_id'=>$state->id; 'name'=>'Jabalpur']));
    // City::create($country=Country::create(['state_id'=>$state->id; 'name'=>'Katni']));
    // City::create($country=Country::create(['state_id'=>$state->id; 'name'=>'Satna']));
    // City::create($country=Country::create(['state_id'=>$state->id; 'name'=>'Ujjain']));

    // $state=State::create($country=Country::create(['country_id'=>$country->id;'name'=>'Uttar Pradesh']));
    // City::create($country=Country::create(['state_id'=>$state->id; 'name'=>'Kanpur']));
    // City::create($country=Country::create(['state_id'=>$state->id; 'name'=>'Lucknow']));
    // City::create($country=Country::create(['state_id'=>$state->id; 'name'=>'Noida']));
    // City::create($country=Country::create(['state_id'=>$state->id; 'name'=>'Etawa']));
    // City::create($country=Country::create(['state_id'=>$state->id; 'name'=>'Agra']));

    // $state=State::create($country=Country::create(['country_id'=>$country->id;'name'=>'Maharashtra']));
    // City::create($country=Country::create(['state_id'=>$state->id; 'name'=>'Mumbai']));
    // City::create($country=Country::create(['state_id'=>$state->id; 'name'=>'Pune']));
    // City::create($country=Country::create(['state_id'=>$state->id; 'name'=>'Noida']));
    // City::create($country=Country::create(['state_id'=>$state->id; 'name'=>'Etawa']));
    // City::create($country=Country::create(['state_id'=>$state->id; 'name'=>'Agra']));

    // $state=State::create($country=Country::create(['country_id'=>$country->id;'name'=>'Himanchal Pradesh']));
    // City::create($country=Country::create(['state_id'=>$state->id; 'name'=>'Shimla']));
    // City::create($country=Country::create(['state_id'=>$state->id; 'name'=>'Dharamsala']));
    // City::create($country=Country::create(['state_id'=>$state->id; 'name'=>'Solan']));
    // City::create($country=Country::create(['state_id'=>$state->id; 'name'=>'Mandi']));
    // City::create($country=Country::create(['state_id'=>$state->id; 'name'=>'Palampur']));
    // City::create($country=Country::create(['state_id'=>$state->id; 'name'=>'Baddi']));
    // City::create($country=Country::create(['state_id'=>$state->id; 'name'=>'Nahan']));
    // City::create($country=Country::create(['state_id'=>$state->id; 'name'=>'Paonta Sahib']));
    // City::create($country=Country::create(['state_id'=>$state->id; 'name'=>'Sundarnagar']));
    // City::create($country=Country::create(['state_id'=>$state->id; 'name'=>'Chamba']));
    // City::create($country=Country::create(['state_id'=>$state->id; 'name'=>'Una']));
    // City::create($country=Country::create(['state_id'=>$state->id; 'name'=>'Kullu']));
    // City::create($country=Country::create(['state_id'=>$state->id; 'name'=>'Hamirpur']));
    // City::create($country=Country::create(['state_id'=>$state->id; 'name'=>'Bilaspur']));
    // City::create($country=Country::create(['state_id'=>$state->id; 'name'=>'Yol Cantonment']));
    // City::create($country=Country::create(['state_id'=>$state->id; 'name'=>'Nalagarh']));
    // City::create($country=Country::create(['state_id'=>$state->id; 'name'=>'Nurpur']));
    // City::create($country=Country::create(['state_id'=>$state->id; 'name'=>'Kangra']));
    // City::create($country=Country::create(['state_id'=>$state->id; 'name'=>'Baijnath Paprola']));
    // City::create($country=Country::create(['state_id'=>$state->id; 'name'=>'Santokhgarh']));

    // $state=State::create($country=Country::create(['country_id'=>$country->id;'name'=>'Kashmeer']));
    // City::create($country=Country::create(['state_id'=>$state->id; 'name'=>'Srinagar']));
    // City::create($country=Country::create(['state_id'=>$state->id; 'name'=>'Jammu']));
    // City::create($country=Country::create(['state_id'=>$state->id; 'name'=>'Anantnag']));

    // $state=State::create($country=Country::create(['country_id'=>$country->id;'name'=>'Tamilnadu']));
    // City::create($country=Country::create(['state_id'=>$state->id; 'name'=>'Chennai']));
    // City::create($country=Country::create(['state_id'=>$state->id; 'name'=>'Coimbatore']));
    // City::create($country=Country::create(['state_id'=>$state->id; 'name'=>'Madurai']));
    // City::create($country=Country::create(['state_id'=>$state->id; 'name'=>'Tiruchirappalli']));
    // City::create($country=Country::create(['state_id'=>$state->id; 'name'=>'Salem']));
    // City::create($country=Country::create(['state_id'=>$state->id; 'name'=>'Tirunelveli']));
    // City::create($country=Country::create(['state_id'=>$state->id; 'name'=>'Tiruppur']));
    // City::create($country=Country::create(['state_id'=>$state->id; 'name'=>'Vellore']));
    // City::create($country=Country::create(['state_id'=>$state->id; 'name'=>'Erode']));
    // City::create($country=Country::create(['state_id'=>$state->id; 'name'=>'Thoothukkudi']));

    // $state=State::create($country=Country::create(['country_id'=>$country->id;'name'=>'Bihar']));
    // City::create($country=Country::create(['state_id'=>$state->id; 'name'=>'Patna']));
    // City::create($country=Country::create(['state_id'=>$state->id; 'name'=>'Muzaffarpur']));
    // City::create($country=Country::create(['state_id'=>$state->id; 'name'=>'Gaya']));
    // City::create($country=Country::create(['state_id'=>$state->id; 'name'=>'Purnia']));
    // City::create($country=Country::create(['state_id'=>$state->id; 'name'=>'Begusarai']));
    // City::create($country=Country::create(['state_id'=>$state->id; 'name'=>'Bihar Sharif']));
    // City::create($country=Country::create(['state_id'=>$state->id; 'name'=>'Darbhanga']));
    // City::create($country=Country::create(['state_id'=>$state->id; 'name'=>'Arrah']));
    // City::create($country=Country::create(['state_id'=>$state->id; 'name'=>'Katihar']));
    // City::create($country=Country::create(['state_id'=>$state->id; 'name'=>'Munger']));

    // $state=State::create($country=Country::create(['country_id'=>$country->id;'name'=>'Andhra Pradesh']));
    // City::create($country=Country::create(['state_id'=>$state->id; 'name'=>'Visakhapatnam']));
    // City::create($country=Country::create(['state_id'=>$state->id; 'name'=>'Vijayawada']));
    // City::create($country=Country::create(['state_id'=>$state->id; 'name'=>'Guntur']));
    // City::create($country=Country::create(['state_id'=>$state->id; 'name'=>'Nellore']));
    // City::create($country=Country::create(['state_id'=>$state->id; 'name'=>'Rajamahendravaram']));
    // City::create($country=Country::create(['state_id'=>$state->id; 'name'=>'Kurnool']));
    // City::create($country=Country::create(['state_id'=>$state->id; 'name'=>'Kakinada']));
    // City::create($country=Country::create(['state_id'=>$state->id; 'name'=>'Tirupati']));
    // City::create($country=Country::create(['state_id'=>$state->id; 'name'=>'Kadapa']));
    // City::create($country=Country::create(['state_id'=>$state->id; 'name'=>'Eluru']));

    // $state=State::create($country=Country::create(['country_id'=>$country->id;'name'=>'Assam']));
    // City::create($country=Country::create(['state_id'=>$state->id; 'name'=>'Guwahati']));
    // City::create($country=Country::create(['state_id'=>$state->id; 'name'=>'Silchar']));
    // City::create($country=Country::create(['state_id'=>$state->id; 'name'=>'Dibrugarh']));
    // City::create($country=Country::create(['state_id'=>$state->id; 'name'=>'Jorhat']));
    // City::create($country=Country::create(['state_id'=>$state->id; 'name'=>'Nagaon']));
    // City::create($country=Country::create(['state_id'=>$state->id; 'name'=>'Bongaigaon']));
    // City::create($country=Country::create(['state_id'=>$state->id; 'name'=>'Tinsukia']));
    // City::create($country=Country::create(['state_id'=>$state->id; 'name'=>'Tezpur']));
    // City::create($country=Country::create(['state_id'=>$state->id; 'name'=>'Dhubri']));
    // City::create($country=Country::create(['state_id'=>$state->id; 'name'=>'Diphu']));

    // $state=State::create($country=Country::create(['country_id'=>$country->id;'name'=>'Chhattisgarh']));
    // City::create($country=Country::create(['state_id'=>$state->id; 'name'=>'Raipur']));
    // City::create($country=Country::create(['state_id'=>$state->id; 'name'=>'Bhilai (Bhilai Nagar)']));
    // City::create($country=Country::create(['state_id'=>$state->id; 'name'=>'Bilaspur']));
    // City::create($country=Country::create(['state_id'=>$state->id; 'name'=>'Korba']));
    // City::create($country=Country::create(['state_id'=>$state->id; 'name'=>'Raj Nandgaon']));
    

    // $state=State::create($country=Country::create(['country_id'=>$country->id;'name'=>'Delhi']));
    //  City::create($country=Country::create(['state_id'=>$state->id; 'name'=>'Lal Kot or Qila Rai Pithora']));
    // City::create($country=Country::create(['state_id'=>$state->id; 'name'=>'Mehrauli']));
    // City::create($country=Country::create(['state_id'=>$state->id; 'name'=>'Siri']));
    // City::create($country=Country::create(['state_id'=>$state->id; 'name'=>'Tughlakabad']));
    // City::create($country=Country::create(['state_id'=>$state->id; 'name'=>'Firozabad']));
    // City::create($country=Country::create(['state_id'=>$state->id; 'name'=>'Shergarh']));
    // City::create($country=Country::create(['state_id'=>$state->id; 'name'=>'Shahjehabanad']));
    // City::create($country=Country::create(['state_id'=>$state->id; 'name'=>'New Delhi']));


    $country=Country::create(['name' => 'Afghanistan','code' => 'AF']);

    $country=Country::create(['name' => 'Åland Islands', 'code' => 'AX']);
    $country=Country::create(['name' => 'Albania', 'code' => 'AL']);
    $country=Country::create(['name' => 'Algeria','code' => 'DZ']);
    $country=Country::create(['name' => 'American Samoa', 'code' => 'AS']);
    $country=Country::create(['name' => 'Andorra','code' => 'AD']);
    $country=Country::create(['name' => 'Angola', 'code' => 'AO']);
    $country=Country::create(['name' => 'Anguilla','code' => 'AI']);
    $country=Country::create(['name' => 'Antarctica', 'code' => 'AQ']);
    $country=Country::create(['name' => 'Antigua and Barbuda','code' => 'AG']);
    $country=Country::create(['name' => 'Argentina', 'code' => 'AR']);
    $country=Country::create(['name' => 'Armenia', 'code' => 'AM']);
    $country=Country::create(['name' => 'Aruba', 'code' => 'AW']);
    $country=Country::create(['name' => 'Australia', 'code' => 'AU']);
    $country=Country::create(['name' => 'Austria', 'code' => 'AT']);
    $country=Country::create(['name' => 'Azerbaijan', 'code' => 'AZ']);
    $country=Country::create(['name' => 'Bahamas', 'code' => 'BS']);
    $country=Country::create(['name' => 'Bahrain', 'code' => 'BH']);
    $country=Country::create(['name' => 'Bangladesh', 'code' => 'BD']);
    $country=Country::create(['name' => 'Barbados', 'code' => 'BB']);
    $country=Country::create(['name' => 'Belarus', 'code' => 'BY']);
    $country=Country::create(['name' => 'Belgium', 'code' => 'BE']);
    $country=Country::create(['name' => 'Belize', 'code' => 'BZ']);
    $country=Country::create(['name' => 'Benin', 'code' => 'BJ']);
    $country=Country::create(['name' => 'Bermuda','code' => 'BM']);
    $country=Country::create(['name' => 'Bhutan', 'code' => 'BT']);
    $country=Country::create(['name' => 'Bolivia, Plurinational State of', 'code' => 'BO']);
    $country=Country::create(['name' => 'Bonaire, Sint Eustatius and Saba', 'code' => 'BQ']);
    $country=Country::create(['name' => 'Bosnia and Herzegovina', 'code' => 'BA']);
    $country=Country::create(['name' => 'Botswana', 'code' => 'BW']);
    $country=Country::create(['name' => 'Bouvet Island', 'code' => 'BV']);
    $country=Country::create(['name' => 'Brazil', 'code' => 'BR']);
    $country=Country::create(['name' => 'British Indian Ocean Territory','code' => 'IO']);
    $country=Country::create(['name' => 'Brunei Darussalam', 'code' => 'BN']);
    $country=Country::create(['name' => 'Bulgaria', 'code' => 'BG']);
    $country=Country::create(['name' => 'Burkina Faso', 'code' => 'BF']);
    $country=Country::create(['name' => 'Burundi', 'code' => 'BI']);
    $country=Country::create(['name' => 'Cambodia', 'code' => 'KH']);
    $country=Country::create(['name' => 'Cameroon', 'code' => 'CM']);
    $country=Country::create(['name' => 'Canada', 'code' => 'CA']);
    $country=Country::create(['name' => 'Cape Verde', 'code' => 'CV']);
    $country=Country::create(['name' => 'Cayman Islands','code' => 'KY']);
    $country=Country::create(['name' => 'Central African Republic','code' => 'CF']);
    $country=Country::create(['name' => 'Chad', 'code' => 'TD']);
    $country=Country::create(['name' => 'Chile', 'code' => 'CL']);
    $country=Country::create(['name' => 'China', 'code' => 'CN']);
    $country=Country::create(['name' => 'Christmas Island', 'code' => 'CX']);
    $country=Country::create(['name' => 'Cocos (Keeling) Islands','code' => 'CC']);
    $country=Country::create(['name' => 'Colombia', 'code' => 'CO']);
    $country=Country::create(['name' => 'Comoros', 'code' => 'KM']);
    $country=Country::create(['name' => 'Congo', 'code' => 'CG']);
    $country=Country::create(['name' => 'Congo; the Democratic Republic of the', 'code' => 'CD']);
    $country=Country::create(['name' => 'Cook Islands', 'code' => 'CK']);
    $country=Country::create(['name' => 'Costa Rica', 'code' => 'CR']);
    $country=Country::create(['name' => 'Côte d\'Ivoire', 'code' => 'CI']);
    $country=Country::create(['name' => 'Croatia', 'code' => 'HR']);
    $country=Country::create(['name' => 'Cuba', 'code' => 'CU']);
    $country=Country::create(['name' => 'Curaçao', 'code' => 'CW']);
    $country=Country::create(['name' => 'Cyprus', 'code' => 'CY']);
    $country=Country::create(['name' => 'Czech Republic', 'code' => 'CZ']);
    $country=Country::create(['name' => 'Denmark', 'code' => 'DK']);
    $country=Country::create(['name' => 'Djibouti', 'code' => 'DJ']);
    $country=Country::create(['name' => 'Dominica', 'code' => 'DM']);
    $country=Country::create(['name' => 'Dominican Republic', 'code' => 'DO']);
    $country=Country::create(['name' => 'Ecuador', 'code' => 'EC']);
    $country=Country::create(['name' => 'Egypt', 'code' => 'EG']);
    $country=Country::create(['name' => 'El Salvador', 'code' => 'SV']);
    $country=Country::create(['name' => 'Equatorial Guinea', 'code' => 'GQ']);
    $country=Country::create(['name' => 'Eritrea', 'code' => 'ER']);
    $country=Country::create(['name' => 'Estonia', 'code' => 'EE']);
    $country=Country::create(['name' => 'Ethiopia', 'code' => 'ET']);
    $country=Country::create(['name' => 'Falkland Islands (Malvinas)', 'code' => 'FK']);
    $country=Country::create(['name' => 'Faroe Islands', 'code' => 'FO']);
    $country=Country::create(['name' => 'Fiji', 'code' => 'FJ']);
    $country=Country::create(['name' => 'Finland', 'code' => 'FI']);
    $country=Country::create(['name' => 'France', 'code' => 'FR']);
    $country=Country::create(['name' => 'French Guiana', 'code' => 'GF']);
    $country=Country::create(['name' => 'French Polynesia', 'code' => 'PF']);
    $country=Country::create(['name' => 'French Southern Territories', 'code' => 'TF']);
    $country=Country::create(['name' => 'Gabon', 'code' => 'GA']);
    $country=Country::create(['name' => 'Gambia', 'code' => 'GM']);
    $country=Country::create(['name' => 'Georgia', 'code' => 'GE']);
    $country=Country::create(['name' => 'Germany', 'code' => 'DE']);
    $country=Country::create(['name' => 'Ghana', 'code' => 'GH']);
    $country=Country::create(['name' => 'Gibraltar', 'code' => 'GI']);
    $country=Country::create(['name' => 'Greece', 'code' => 'GR']);
    $country=Country::create(['name' => 'Greenland', 'code' => 'GL']);
    $country=Country::create(['name' => 'Grenada', 'code' => 'GD']);
    $country=Country::create(['name' => 'Guadeloupe', 'code' => 'GP']);
    $country=Country::create(['name' => 'Guam', 'code' => 'GU']);
    $country=Country::create(['name' => 'Guatemala', 'code' => 'GT']);
    $country=Country::create(['name' => 'Guernsey', 'code' => 'GG']);
    $country=Country::create(['name' => 'Guinea', 'code' => 'GN']);
    $country=Country::create(['name' => 'Guinea-Bissau', 'code' => 'GW']);
    $country=Country::create(['name' => 'Guyana', 'code' => 'GY']);
    $country=Country::create(['name' => 'Haiti', 'code' => 'HT']);
    $country=Country::create(['name' => 'Heard Island and McDonald Mcdonald Islands', 'code' => 'HM']);
    $country=Country::create(['name' => 'Holy See (Vatican City State)', 'code' => 'VA']);
    $country=Country::create(['name' => 'Honduras', 'code' => 'HN']);
    $country=Country::create(['name' => 'Hong Kong', 'code' => 'HK']);
    $country=Country::create(['name' => 'Hungary', 'code' => 'HU']);
    $country=Country::create(['name' => 'Iceland', 'code' => 'IS']);

    $country=Country::create(['name' => 'India', 'code' => 'IN']);
    $state=State::create(['country_id'=>$country->id, "name" => "Andaman and Nicobar", "code" => "AN"]);
     $state=State::create(['country_id'=>$country->id, "name" => "Arunachal Pradesh", "code" => "AR"]);
     $state=State::create(['country_id'=>$country->id, "name" => "Andhra Pradesh", "code" => "AP"]);
     $state=State::create(['country_id'=>$country->id, "name" => "Assam", "code" => "AS"]);
     $state=State::create(['country_id'=>$country->id, "name" => "Bihar", "code" => "BR"]);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Patna']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Muzaffarpur']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Gaya']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Purnia']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Begusarai']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Bhagalpur']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Bihar Sharif']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Darbhanga']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Arrah']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Katihar']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Munger']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Chhapra']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Mehsi']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Danapur']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Bettiah']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Saharsa']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Hajipur']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Sasaram']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Dehri']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Siwan']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Motihari']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Nawada']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Bagaha']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Buxar']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Kishanganj']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Sitamarhi']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Jamalpur']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Jehanabad']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Aurangabad']);

     $state=State::create(['country_id'=>$country->id, "name" => "Chandigarh", "code" => "CH"]);
     $state=State::create(['country_id'=>$country->id, "name" => "Chhattisgarh", "code" => "CG"]);
     $state=State::create(['country_id'=>$country->id, "name" => "Daman and Diu", "code" => "DD"]);
     $state=State::create(['country_id'=>$country->id, "name" => "Dadra and Nagar Haveli", "code" => "DD"]);
     $state=State::create(['country_id'=>$country->id, "name" => "Gujarat", "code" => "GJ"]);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Ahmedabad']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Surat']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Vadodara']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Rajkot']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Bhavnagar']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Jamnagar']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Gandhinagar']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Junagadh']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Gandhidham']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Anand']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Navsari']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Morbi']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Nadiad']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Surendranagar']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Bharuch']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Mehsana']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Bhuj']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Porbandar']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Palanpur']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Valsad']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Vapi']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Gondal']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Veraval']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Godhra']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Patan']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Kalol']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Dahod']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Botad']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Amreli']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Kalol']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Dahod']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Botad']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Amreli']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Deesa']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Jetpur']);

     $state=State::create(['country_id'=>$country->id, "name" => "Goa", "code" => "GA"]);
     $state=State::create(['country_id'=>$country->id, "name" => "Himachal Pradesh", "code" => "HP"]);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Shimla']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Dharamsala']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Solan']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Mandi']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Palampur']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Baddi']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Nahan']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Paonta Sahib']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Sundarnagar']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Chamba']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Una']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Kullu']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Hamirpur']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Bilaspur']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Yol Cantonment']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Nalagarh']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Nurpur']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Kangra']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Baijnath Paprola']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Santokhgarh']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Mehatpur Basdehra']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Shamshi']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Parwanoo']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Manali']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Tira Sujanpur']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Ghumarwin']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Dalhousie']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Rohru']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Nagrota Bagwan']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Rampur']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Jawalamukhi']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Jogindernagar']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Dera Gopipur']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Sarkaghat']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Jhakhri']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Indora']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Bhuntar']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Nadaun']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Theog']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Kasauli Cantonment']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Gagret']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Chuari Khas']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Daulatpur']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Sabathu Cantonment']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Dalhousie Cantonment']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Rajgarh']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Arki']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Dagshai Cantonment']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Seoni']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Talai']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Jutogh Cantonment']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Chaupal']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Rewalsar']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Bakloh Cantonment']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Jubbal']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Bhota']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Banjar']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Naina Devi']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Kotkhai']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Narkanda']);


     $state=State::create(['country_id'=>$country->id, "name" => "Haryana", "code" => "HR"]);
     $state=State::create(['country_id'=>$country->id, "name" => "Jharkhand", "code" => "JH"]);
     $state=State::create(['country_id'=>$country->id, "name" => "Jammu & Kashmir", "code" => "JK"]);
     $state=State::create(['country_id'=>$country->id, "name" => "Kerala", "code" => "KL"]);
     $state=State::create(['country_id'=>$country->id, "name" => "Karnataka", "code" => "KA"]);
     $state=State::create(['country_id'=>$country->id, "name" => "Lakshadweep", "code" => "LD"]);
     $state=State::create(['country_id'=>$country->id, "name" => "Leh-Ladakh", "code" => "LA"]);
     $state=State::create(['country_id'=>$country->id, "name" => "Maharashtra", "code" => "MH"]);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Mumbai']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Pune']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Nagpur']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Thane']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Pimpri-Chinchwad']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Nashik']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Kalyan-Dombivli']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Vasai-Virar']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Chhatrapati Sambhajinagar']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Navi Mumbai']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Solapur']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Mira-Bhayandar']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Bhiwandi-Nizampur']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Jalgaon']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Amravati']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Nanded-Waghala']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Kolhapur']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Ulhasnagar']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Sangli-Miraj-Kupwad']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Malegaon']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Akola']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Latur']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Dhule']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Ahmednagar']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Chandrapur']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Parbhani']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Ichalkaranji']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Jalna']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Ambarnath']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Bhusawal']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Panvel']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Badlapur']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Beed']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Gondia']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Satara']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Barshi']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Yavatmal']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Achalpur']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Dharashiv']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Nandurbar']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Wardha']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Udgir']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Hinganghat']);

     $state=State::create(['country_id'=>$country->id, "name" => "Manipur", "code" => "MN"]);
     $state=State::create(['country_id'=>$country->id, "name" => "Madhya Pradesh", "code" => "MP"]);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Indore']);
      City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Bhopal']);
      City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Jabalpur']);
      City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Gwalior']);
      City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Ujjain']);
      City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Sagar']);
      City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Dewas']);
      City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Satna']);
      City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Ratlam']);
      City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Rewa']);
      City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Katni']);
      City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Singrauli']);
      City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Burhanpur']);
      City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Khandwa']);
      City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Bhind']);
      City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Chhindwara']);
      City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Guna']);
      City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Shivpuri']);
      City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Vidisha']);
      City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Chhatarpur']);
      City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Damoh']);
      City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Mandsaur']);
      City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Khargone']);
      City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Neemuch']);
      City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Pithampur']);
      City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Narmadapuram']);
      City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Itarsi']);
      City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Sehore']);
      City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Chambal']);
      City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Betul']);
      City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Seoni']);
      City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Datia']);
      City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Nagda']);
      City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Dindori']);
     
     $state=State::create(['country_id'=>$country->id, "name" => "Mizoram", "code" => "MZ"]);
     $state=State::create(['country_id'=>$country->id, "name" => "Meghalaya", "code" => "ML"]);
     $state=State::create(['country_id'=>$country->id, "name" => "Delhi", "code" => "DL"]);
     $state=State::create(['country_id'=>$country->id, "name" => "Nagaland", "code" => "NL"]);
     $state=State::create(['country_id'=>$country->id, "name" => "Odisha", "code" => "OD"]);
     $state=State::create(['country_id'=>$country->id, "name" => "Puducherry", "code" => "PY"]);
     $state=State::create(['country_id'=>$country->id, "name" => "Punjab", "code" => "PB"]);
     $state=State::create(['country_id'=>$country->id, "name" => "Rajasthan", "code" => "RJ"]);
     $state=State::create(['country_id'=>$country->id, "name" => "Sikkim", "code" => "SK"]);
     $state=State::create(['country_id'=>$country->id, "name" => "Tamil Nadu", "code" => "TN"]);
     $state=State::create(['country_id'=>$country->id, "name" => "Telangana", "code" => "TS"]);
     $state=State::create(['country_id'=>$country->id, "name" => "Tripura", "code" => "TR"]);
     $state=State::create(['country_id'=>$country->id, "name" => "Uttar Pradesh", "code" => "UP"]);
      City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Kanpur']);
      City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Lucknow']);
      City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Ghaziabad']);
      City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Agra']);
      City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Meerut']);
      City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Varanasi']);
      City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Prayagraj']);
      City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Bareilly']);
      City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Aligarh']);
      City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Moradabad']);
      City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Saharanpur']);
      City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Gorakhpur']);
      City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Noida']);
      City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Firozabad']);
      City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Jhansi']);
      City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Muzaffarnagar']);
      City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Mathura']);
      City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Ayodhya']);
      City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Rampur']);
      City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Shahjahanpur']);
      City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Farrukhabad']);
      City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Baduan']);
      City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Maunath Bhanjan']);
      City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Hapur']);
      City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Etawah']);
      City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Mirzapur-cum-Vindhyachal']);
      City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Bulandshahr']);
      City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Sambhal']);
      City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Amroha']);
      City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Hardoi']);
      City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Fatehpur']);
      City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Raebareli']);
      City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Orai']);
      City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Sitapur']);
      City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Bahraich']);
      City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Modinagar']);
      City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Unnao']);
      City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Jaunpur']);
      City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Lakhimpur']);
      City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Hathras']);
      City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Banda']);
      City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Pilibhit']);
      City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Barabanki']);
      City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Khurja']);
      City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Gonda']);
      City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Mainpuri']);
      City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Lalitpur']);
      City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Etah']);
      City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Deoria']);
      City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Badaun']);
      City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Ghazipur']);
      City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Sultanpur']);
      City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Azamgarh']);
      City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Bijnor']);
      City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Sahaswan']);
      City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Basti']);
      City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Chandausi']);
      City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Akbarpur']);
      City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Ballia']);
      City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Tanda']);
      City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Greater Noida']);
      City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Shikohabad']);
      City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Shamli']);
      City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Awagarh']);
      City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Kasganj']);

     $state=State::create(['country_id'=>$country->id, "name" => "Uttarakhand", "code" => "UK"]);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Dehradun']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Haridwar']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Roorkee']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Haldwani-cum-Kathgodam']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Rudrapur']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Kashipur']);
     City::create(['country_id'=>$country->id, 'state_id'=>$state->id, 'name'=>'Rishikesh']);

     $state=State::create(['country_id'=>$country->id, "name" => "West Bengal", "code" => "WB"]);


    $country=Country::create(['name' => 'Indonesia', 'code' => 'ID']);
    $country=Country::create(['name' => 'Iran; Islamic Republic of', 'code' => 'IR']);
    $country=Country::create(['name' => 'Iraq', 'code' => 'IQ']);
    $country=Country::create(['name' => 'Ireland', 'code' => 'IE']);
    $country=Country::create(['name' => 'Isle of Man', 'code' => 'IM']);
    $country=Country::create(['name' => 'Israel', 'code' => 'IL']);
    $country=Country::create(['name' => 'Italy', 'code' => 'IT']);
    $country=Country::create(['name' => 'Jamaica', 'code' => 'JM']);
    $country=Country::create(['name' => 'Japan', 'code' => 'JP']);
    $country=Country::create(['name' => 'Jersey', 'code' => 'JE']);
    $country=Country::create(['name' => 'Jordan', 'code' => 'JO']);
    $country=Country::create(['name' => 'Kazakhstan', 'code' => 'KZ']);
    $country=Country::create(['name' => 'Kenya', 'code' => 'KE']);
    $country=Country::create(['name' => 'Kiribati', 'code' => 'KI']);
    $country=Country::create(['name' => 'Korea, Democratic People\'s Republic of', 'code' => 'KP']);
    $country=Country::create(['name' => 'Korea; Republic of', 'code' => 'KR']);
    $country=Country::create(['name' => 'Kuwait', 'code' => 'KW']);
    $country=Country::create(['name' => 'Kyrgyzstan', 'code' => 'KG']);
    $country=Country::create(['name' => 'Lao People\'s Democratic Republic', 'code' => 'LA']);
    $country=Country::create(['name' => 'Latvia', 'code' => 'LV']);
    $country=Country::create(['name' => 'Lebanon', 'code' => 'LB']);
    $country=Country::create(['name' => 'Lesotho', 'code' => 'LS']);
    $country=Country::create(['name' => 'Liberia', 'code' => 'LR']);
    $country=Country::create(['name' => 'Libya', 'code' => 'LY']);
    $country=Country::create(['name' => 'Liechtenstein', 'code' => 'LI']);
    $country=Country::create(['name' => 'Lithuania', 'code' => 'LT']);
    $country=Country::create(['name' => 'Luxembourg', 'code' => 'LU']);
    $country=Country::create(['name' => 'Macao', 'code' => 'MO']);
    $country=Country::create(['name' => 'Macedonia; the Former Yugoslav Republic of', 'code' => 'MK']);
    $country=Country::create(['name' => 'Madagascar', 'code' => 'MG']);
    $country=Country::create(['name' => 'Malawi', 'code' => 'MW']);
    $country=Country::create(['name' => 'Malaysia', 'code' => 'MY']);
    $country=Country::create(['name' => 'Maldives', 'code' => 'MV']);
    $country=Country::create(['name' => 'Mali', 'code' => 'ML']);
    $country=Country::create(['name' => 'Malta', 'code' => 'MT']);
    $country=Country::create(['name' => 'Marshall Islands', 'code' => 'MH']);
    $country=Country::create(['name' => 'Martinique', 'code' => 'MQ']);
    $country=Country::create(['name' => 'Mauritania', 'code' => 'MR']);
    $country=Country::create(['name' => 'Mauritius', 'code' => 'MU']);
    $country=Country::create(['name' => 'Mayotte', 'code' => 'YT']);
    $country=Country::create(['name' => 'Mexico', 'code' => 'MX']);
    $country=Country::create(['name' => 'Micronesia, Federated States of', 'code' => 'FM']);
    $country=Country::create(['name' => 'Moldova, Republic of', 'code' => 'MD']);
    $country=Country::create(['name' => 'Monaco', 'code' => 'MC']);
    $country=Country::create(['name' => 'Mongolia', 'code' => 'MN']);
    $country=Country::create(['name' => 'Montenegro', 'code' => 'ME']);
    $country=Country::create(['name' => 'Montserrat', 'code' => 'MS']);
    $country=Country::create(['name' => 'Morocco', 'code' => 'MA']);
    $country=Country::create(['name' => 'Mozambique', 'code' => 'MZ']);
    $country=Country::create(['name' => 'Myanmar', 'code' => 'MM']);
    $country=Country::create(['name' => 'Namibia', 'code' => 'NA']);
    $country=Country::create(['name' => 'Nauru', 'code' => 'NR']);
    $country=Country::create(['name' => 'Nepal', 'code' => 'NP']);
    $country=Country::create(['name' => 'Netherlands', 'code' => 'NL']);
    $country=Country::create(['name' => 'New Caledonia', 'code' => 'NC']);
    $country=Country::create(['name' => 'New Zealand', 'code' => 'NZ']);
    $country=Country::create(['name' => 'Nicaragua', 'code' => 'NI']);
    $country=Country::create(['name' => 'Niger', 'code' => 'NE']);
    $country=Country::create(['name' => 'Nigeria', 'code' => 'NG']);
    $country=Country::create(['name' => 'Niue', 'code' => 'NU']);
    $country=Country::create(['name' => 'Norfolk Island', 'code' => 'NF']);
    $country=Country::create(['name' => 'Northern Mariana Islands', 'code' => 'MP']);
    $country=Country::create(['name' => 'Norway', 'code' => 'NO']);
    $country=Country::create(['name' => 'Oman', 'code' => 'OM']);
    $country=Country::create(['name' => 'Pakistan','code' => 'PK']);
    $country=Country::create(['name' => 'Palau', 'code' => 'PW']);
    $country=Country::create(['name' => 'Palestine; State of', 'code' => 'PS']);
    $country=Country::create(['name' => 'Panama', 'code' => 'PA']);
    $country=Country::create(['name' => 'Papua New Guinea', 'code' => 'PG']);
    $country=Country::create(['name' => 'Paraguay', 'code' => 'PY']);
    $country=Country::create(['name' => 'Peru', 'code' => 'PE']);
    $country=Country::create(['name' => 'Philippines','code' => 'PH']);
    $country=Country::create(['name' => 'Pitcairn', 'code' => 'PN']);
    $country=Country::create(['name' => 'Poland', 'code' => 'PL']);
    $country=Country::create(['name' => 'Portugal', 'code' => 'PT']);
    $country=Country::create(['name' => 'Puerto Rico', 'code' => 'PR']);
    $country=Country::create(['name' => 'Qatar', 'code' => 'QA']);
    $country=Country::create(['name' => 'Réunion', 'code' => 'RE']);
    $country=Country::create(['name' => 'Romania', 'code' => 'RO']);
    $country=Country::create(['name' => 'Russian Federation', 'code' => 'RU']);
    $country=Country::create(['name' => 'Rwanda', 'code' => 'RW']);
    $country=Country::create(['name' => 'Saint Barthélemy', 'code' => 'BL']);
    $country=Country::create(['name' => 'Saint Helena; Ascension and Tristan da Cunha', 'code' => 'SH']);
    $country=Country::create(['name' => 'Saint Kitts and Nevis', 'code' => 'KN']);
    $country=Country::create(['name' => 'Saint Lucia', 'code' => 'LC']);
    $country=Country::create(['name' => 'Saint Martin (French part)', 'code' => 'MF']);
    $country=Country::create(['name' => 'Saint Pierre and Miquelon', 'code' => 'PM']);
    $country=Country::create(['name' => 'Saint Vincent and the Grenadines', 'code' => 'VC']);
    $country=Country::create(['name' => 'Samoa', 'code' => 'WS']);
    $country=Country::create(['name' => 'San Marino', 'code' => 'SM']);
    $country=Country::create(['name' => 'Sao Tome and Principe', 'code' => 'ST']);
    $country=Country::create(['name' => 'Saudi Arabia', 'code' => 'SA']);
    $country=Country::create(['name' => 'Senegal', 'code' => 'SN']);
    $country=Country::create(['name' => 'Serbia', 'code' => 'RS']);
    $country=Country::create(['name' => 'Seychelles', 'code' => 'SC']);
    $country=Country::create(['name' => 'Sierra Leone', 'code' => 'SL']);
    $country=Country::create(['name' => 'Singapore', 'code' => 'SG']);
    $country=Country::create(['name' => 'Sint Maarten (Dutch part)', 'code' => 'SX']);
    $country=Country::create(['name' => 'Slovakia', 'code' => 'SK']);
    $country=Country::create(['name' => 'Slovenia', 'code' => 'SI']);
    $country=Country::create(['name' => 'Solomon Islands', 'code' => 'SB']);
    $country=Country::create(['name' => 'Somalia', 'code' => 'SO']);
    $country=Country::create(['name' => 'South Africa', 'code' => 'ZA']);
    $country=Country::create(['name' => 'South Georgia and the South Sandwich Islands', 'code' => 'GS']);
    $country=Country::create(['name' => 'South Sudan', 'code' => 'SS']);
    $country=Country::create(['name' => 'Spain', 'code' => 'ES']);
    $country=Country::create(['name' => 'Sri Lanka', 'code' => 'LK']);

    $state=State::create(['country_id'=>$country->id, "name" => "Central", "code" => ""]);
    City::create(['country_id'=>$country->id,'state_id'=>$state->id, 'name'=>'Dambulla']);
    
    $country=Country::create(['name' => 'Sudan', 'code' => 'SD']);
    $country=Country::create(['name' => 'Suriname', 'code' => 'SR']);
    $country=Country::create(['name' => 'Svalbard and Jan Mayen', 'code' => 'SJ']);
    $country=Country::create(['name' => 'Swaziland', 'code' => 'SZ']);
    $country=Country::create(['name' => 'Sweden', 'code' => 'SE']);
    $country=Country::create(['name' => 'Switzerland', 'code' => 'CH']);
    $country=Country::create(['name' => 'Syrian Arab Republic', 'code' => 'SY']);
    $country=Country::create(['name' => 'Taiwan', 'code' => 'TW']);
    $country=Country::create(['name' => 'Tajikistan', 'code' => 'TJ']);
    $country=Country::create(['name' => 'Tanzania; United Republic of', 'code' => 'TZ']);
    $country=Country::create(['name' => 'Thailand', 'code' => 'TH']);
    $country=Country::create(['name' => 'Timor-Leste', 'code' => 'TL']);
    $country=Country::create(['name' => 'Togo', 'code' => 'TG']);
    $country=Country::create(['name' => 'Tokelau', 'code' => 'TK']);
    $country=Country::create(['name' => 'Tonga', 'code' => 'TO']);
    $country=Country::create(['name' => 'Trinidad and Tobago', 'code' => 'TT']);
    $country=Country::create(['name' => 'Tunisia', 'code' => 'TN']);
    $country=Country::create(['name' => 'Turkey', 'code' => 'TR']);
    $country=Country::create(['name' => 'Turkmenistan', 'code' => 'TM']);
    $country=Country::create(['name' => 'Turks and Caicos Islands', 'code' => 'TC']);
    $country=Country::create(['name' => 'Tuvalu', 'code' => 'TV']);
    $country=Country::create(['name' => 'Uganda', 'code' => 'UG']);
    $country=Country::create(['name' => 'Ukraine', 'code' => 'UA']);
    $country=Country::create(['name' => 'United Arab Emirates', 'code' => 'AE']);
    $country=Country::create(['name' => 'United Kingdom', 'code' => 'GB']);
    $country=Country::create(['name' => 'United States', 'code' => 'US']);
     //$state=State::create(['country_id'=>$country->id,'name'=>'Gujrat']);
     $state=State::create(['country_id'=>$country->id, "name" => "Alabama", "code" => "AL"]);
     $state=State::create(['country_id'=>$country->id, "name" => "Alaska", "code" => "AK"]);
     $state=State::create(['country_id'=>$country->id, "name" => "Arizona", "code" => "AZ"]);
     $state=State::create(['country_id'=>$country->id, "name" => "Arkansas", "code" => "AR"]);
     $state=State::create(['country_id'=>$country->id, "name" => "California", "code" => "CA"]);
     City::create(['country_id'=>$country->id,'state_id'=>$state->id, 'name'=>'California']);
     $state=State::create(['country_id'=>$country->id, "name" => "Colorado", "code" => "CO"]);
     $state=State::create(['country_id'=>$country->id, "name" => "Connecticut", "code" => "CT"]);
     $state=State::create(['country_id'=>$country->id, "name" => "Delaware", "code" => "DE"]);
     $state=State::create(['country_id'=>$country->id, "name" => "District of Columbia", "code" => "DC"]);
     $state=State::create(['country_id'=>$country->id, "name" => "Florida", "code" => "FL"]);
     $state=State::create(['country_id'=>$country->id, "name" => "Georgia", "code" => "GA"]);
     $state=State::create(['country_id'=>$country->id, "name" => "Hawaii", "code" => "HI"]);
     $state=State::create(['country_id'=>$country->id, "name" => "Idaho", "code" => "ID"]);
     $state=State::create(['country_id'=>$country->id, "name" => "Illinois", "code" => "IL"]);
     $state=State::create(['country_id'=>$country->id, "name" => "Indiana", "code" => "IN"]);
     $state=State::create(['country_id'=>$country->id, "name" => "Iowa", "code" => "IA"]);
     $state=State::create(['country_id'=>$country->id, "name" => "Kansas", "code" => "KS"]);
     $state=State::create(['country_id'=>$country->id, "name" => "Kentucky", "code" => "KY"]);
     $state=State::create(['country_id'=>$country->id, "name" => "Louisiana", "code" => "LA"]);
     $state=State::create(['country_id'=>$country->id, "name" => "Maine", "code" => "ME"]);
     $state=State::create(['country_id'=>$country->id, "name" => "Maryland", "code" => "MD"]);
     $state=State::create(['country_id'=>$country->id, "name" => "Massachusetts", "code" => "MA"]);
     $state=State::create(['country_id'=>$country->id, "name" => "Michigan", "code" => "MI"]);
     $state=State::create(['country_id'=>$country->id, "name" => "Minnesota", "code" => "MN"]);
     $state=State::create(['country_id'=>$country->id, "name" => "Mississippi", "code" => "MS"]);
     $state=State::create(['country_id'=>$country->id, "name" => "Missouri", "code" => "MO"]);
     $state=State::create(['country_id'=>$country->id, "name" => "Montana", "code" => "MT"]);
     $state=State::create(['country_id'=>$country->id, "name" => "Nebraska", "code" => "NE"]);
     $state=State::create(['country_id'=>$country->id, "name" => "Nevada", "code" => "NV"]);
     $state=State::create(['country_id'=>$country->id, "name" => "New Hampshire", "code" => "NH"]);
     $state=State::create(['country_id'=>$country->id, "name" => "New Jersey", "code" => "NJ"]);
     $state=State::create(['country_id'=>$country->id, "name" => "New Mexico", "code" => "NM"]);
     $state=State::create(['country_id'=>$country->id, "name" => "New Mexico", "code" => "NM"]);
     $state=State::create(['country_id'=>$country->id, "name" => "New York", "code" => "NY"]);
     $state=State::create(['country_id'=>$country->id, "name" => "North Carolina", "code" => "NC"]);
     $state=State::create(['country_id'=>$country->id, "name" => "North Dakota", "code" => "ND"]);
     $state=State::create(['country_id'=>$country->id, "name" => "Ohio", "code" => "OH"]);
     $state=State::create(['country_id'=>$country->id, "name" => "Oklahoma", "code" => "OK"]);
     $state=State::create(['country_id'=>$country->id, "name" => "Oregon", "code" => "OR"]);
     $state=State::create(['country_id'=>$country->id, "name" => "Pennsylvania", "code" => "PA"]);
     $state=State::create(['country_id'=>$country->id, "name" => "Rhode Island", "code" => "RI"]);
     $state=State::create(['country_id'=>$country->id, "name" => "South Carolina", "code" => "SC"]);
     $state=State::create(['country_id'=>$country->id, "name" => "South Dakota", "code" => "SD"]);
     $state=State::create(['country_id'=>$country->id, "name" => "Tennessee", "code" => "TN"]);
     $state=State::create(['country_id'=>$country->id, "name" => "Texas", "code" => "TX"]);
     $state=State::create(['country_id'=>$country->id, "name" => "Utah", "code" => "UT"]);
     $state=State::create(['country_id'=>$country->id, "name" => "Vermont", "code" => "VT"]);
     $state=State::create(['country_id'=>$country->id, "name" => "Virginia", "code" => "VA"]);
     $state=State::create(['country_id'=>$country->id, "name" => "Washington", "code" => "WA"]);
     $state=State::create(['country_id'=>$country->id, "name" => "West Virginia", "code" => "WV"]);
     $state=State::create(['country_id'=>$country->id, "name" => "Wisconsin", "code" => "WI"]);
     $state=State::create(['country_id'=>$country->id, "name" => "Wyoming", "code" => "WY"]);


    $country=Country::create(['name' => 'United States Minor Outlying Islands', 'code' => 'UM']);
    $country=Country::create(['name' => 'Uruguay', 'code' => 'UY']);
    $country=Country::create(['name' => 'Uzbekistan', 'code' => 'UZ']);
    $country=Country::create(['name' => 'Vanuatu', 'code' => 'VU']);
    $country=Country::create(['name' => 'Venezuela; Bolivarian Republic of', 'code' => 'VE']);
    $country=Country::create(['name' => 'Viet Nam', 'code' => 'VN']);
    $country=Country::create(['name' => 'Virgin Islands; British', 'code' => 'VG']);
    $country=Country::create(['name' => 'Virgin Islands; U.S.', 'code' => 'VI']);
    $country=Country::create(['name' => 'Wallis and Futuna', 'code' => 'WF']);
    $country=Country::create(['name' => 'Western Sahara', 'code' => 'EH']);
    $country=Country::create(['name' => 'Yemen', 'code' => 'YE']);
    $country=Country::create(['name' => 'Zambia', 'code' => 'ZM']);
    $country=Country::create(['name' => 'Zimbabwe', 'code' => 'ZW']);

     }

    
}
